object Dependencies {
    const val SPRING_STARTER_JPA = "org.springframework.boot:spring-boot-starter-data-jpa"
    const val SPRING_STARTER_SECURITY = "org.springframework.boot:spring-boot-starter-security"
    const val SPRING_WEB = "org.springframework.boot:spring-boot-starter-web"
    const val KOTLIN_JACKSON = "com.fasterxml.jackson.module:jackson-module-kotlin"
    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect"
    const val MYSQL = "com.mysql:mysql-connector-j"
    const val SPRING_STARTER_TEST = "org.springframework.boot:spring-boot-starter-test"
    const val SPRING_SECURITY_TEST = "org.springframework.security:spring-security-test"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    const val KTLINT = "com.pinterest:ktlint:${DependencyVersions.KTLINT_VERSION}"
    const val VALIDATION = "org.springframework.boot:spring-boot-starter-validation"
    const val SENTRY = "io.sentry:sentry-spring-boot-starter:${DependencyVersions.SENTRY_VERSION}"
    const val CONFIGURATION_PROCESSOR = "org.springframework.boot:spring-boot-configuration-processor"
}